name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.HUB_USER }}/hackatonapp:latest . -f HackatonApp/Dockerfile
        docker push ${{ secrets.HUB_USER }}/hackatonapp:latest
